### ISSUE TITLE
Closes before all downloads finished

### ISSUE THREAD

**Issue by Nezzy2** [thefiz/TwitchClipDownloader#3] opened 2018-05-13 04:44 UTC
The console says every one is downloaded then it closes after about 5 minutes with some clips not being finished

**Comment by thefiz** [comment] 2018-05-13 05:00
I haven't run into this, let me double check.  If you could send or attach the clips.txt file you are using, I could verify

**Comment by Nezzy2** [comment] 2018-05-13 05:02
[clips.txt](https://github.com/thefiz/TwitchClipDownloader/files/1998115/clips.txt)

**Comment by thefiz** [comment] 2018-05-13 05:42
Is the issue that some of the clips are files, but they're ~200 bytes?  If so, I believe this is the same issue as I was looking at with someone else.

**Comment by thefiz** [comment] 2018-05-13 20:53
Closing - Duplicate of #1

**Closed as completed by thefiz** 2018-05-13 20:53 UTC
